config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'


    resources :users, only: [:new, :create, :show]

    resources :sessions, only: [:new, :create, :destroy]

    resources :labels, only: [:show]

  get 'about' => 'welcome#about'

  post 'users/confirm' => 'users#confirm'

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments,  only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:new, :edit] do
        resources :posts, except: [:new, :edit]
      end
      resources :comments, only: [:index, :show]
    end
  end

end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  value      :integer
#  user_id    :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote" }, presence: true

  private

  def update_post
    post.update_rank
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :require_sign_in

  def up_vote
    update_vote(1)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def down_vote
    update_vote(-1)
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def update_vote(new_value)
    @post = Post.find(params[:post_id])
    @vote = @post.votes.where(user_id: current_user.id).first

    if @vote
      @vote.update_attribute(:value, new_value)
    else
      @vote = current_user.votes.create(value: new_value, post: @post)
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_voter.html.erb
<% if current_user %>
  <div class="vote-arrows pull-left">
    <div>
      <%= link_to " ", post_up_vote_path(post),
      class: 'glyphicon glyphicon-chevron-up', method: :post, remote: true %>
    </div>

    <div id="post-<%=post.id %>-vote">
      <strong><%= post.points %></strong>
    </div>

    <div>
      <%= link_to " ", post_down_vote_path(post),
      class: 'glyphicon glyphicon-chevron-down', method: :post, remote: true %>
    </div>
  </div>
<% end %>

app/views/votes/down_vote.js.erb
$('#post-<%= @post.id %>-vote').html("<strong><%= @post.points %></strong>");

app/views/votes/up_vote.js.erb
$('#post-<%= @post.id %>-vote').html("<strong><%= @post.points %></strong>");